# Generated by Django 3.2.8 on 2021-10-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sales',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
