# Generated by Django 3.2.8 on 2021-10-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
    ]
